name: Build Wheels

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels
    runs-on: windows-latest
    strategy:
      matrix:
        pyver: ["3.9"]
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade build setuptools wheel

      - name: Build Wheel
        run: |
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: 'wheels'
          path: ./dist/*.whl
